# Generated by Django 5.1.6 on 2026-02-02 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                ("domain", models.CharField(max_length=255)),
                ("is_accessible", models.BooleanField(default=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "protection_detected",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tech_stack", models.JSONField(blank=True, default=list)),
                ("total_pages", models.IntegerField(default=0)),
                ("total_subdomains", models.IntegerField(default=0)),
                ("total_paths", models.IntegerField(default=0)),
                ("content_types_count", models.IntegerField(default=0)),
                ("include_subdomains", models.BooleanField(default=False)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                ("analysis_duration", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat d'analyse",
                "verbose_name_plural": "Résultats d'analyse",
                "db_table": "analysis_results",
                "ordering": ["-analyzed_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(default="📦", max_length=10)),
                ("count", models.IntegerField(default=0)),
                ("selector", models.CharField(blank=True, max_length=500, null=True)),
                ("detected_fields", models.JSONField(blank=True, default=list)),
                ("preview_items", models.JSONField(blank=True, default=list)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_types",
                        to="api.analysisresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de contenu",
                "verbose_name_plural": "Types de contenu",
                "db_table": "content_types",
            },
        ),
        migrations.CreateModel(
            name="PathDiscovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=2000)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("is_main_page", models.BooleanField(default=False)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("text_preview", models.TextField(blank=True, null=True)),
                ("total_links", models.IntegerField(default=0)),
                ("total_images", models.IntegerField(default=0)),
                ("total_forms", models.IntegerField(default=0)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths",
                        to="api.analysisresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chemin découvert",
                "verbose_name_plural": "Chemins découverts",
                "db_table": "path_discoveries",
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="PageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src", models.URLField(max_length=2000)),
                ("alt", models.CharField(blank=True, max_length=500, null=True)),
                ("width", models.CharField(blank=True, max_length=20, null=True)),
                ("height", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.pathdiscovery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image de page",
                "verbose_name_plural": "Images de page",
                "db_table": "page_images",
            },
        ),
        migrations.CreateModel(
            name="SubdomainDiscovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subdomain", models.CharField(max_length=255)),
                ("is_scrapable", models.BooleanField(default=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("protection", models.CharField(blank=True, max_length=100, null=True)),
                ("source", models.CharField(max_length=50)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subdomains",
                        to="api.analysisresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-domaine découvert",
                "verbose_name_plural": "Sous-domaines découverts",
                "db_table": "subdomain_discoveries",
                "ordering": ["subdomain"],
            },
        ),
    ]
