# Generated by Django 5.1.6 on 2026-02-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_apikey_webhook"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingsession",
            name="current_step",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="scrapingsession",
            name="progress_logs",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
