# Generated by Django 5.1.6 on 2026-02-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_scrapingsession_current_step_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
