# Generated by Django 5.1.6 on 2026-02-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_user_avatar_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_code_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
