# Generated by Django 5.1.6 on 2026-02-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_user_is_2fa_enabled_user_two_factor_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
