# Generated by Django 5.1.6 on 2026-02-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_user_email_verification_token_user_is_email_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnownPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(db_index=True, max_length=255)),
                ("url", models.URLField(max_length=2000)),
                ("path", models.CharField(max_length=2000)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chemin connu",
                "verbose_name_plural": "Chemins connus",
                "db_table": "known_paths",
                "indexes": [
                    models.Index(
                        fields=["domain", "path"], name="known_paths_domain_76ed62_idx"
                    )
                ],
                "unique_together": {("domain", "path")},
            },
        ),
    ]
